version: '3.1'

services:
  php:
    build: ./
    ports: 
      - 8081:80

  db:
    # image: mariadb:10.6
    image: mysql
    # for mysql, NOT mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1